Week-1-assignments-completed
pesto-students/p13-chirag-udeshi-koushikk655 pull request #2
Opened 2023-08-12 05:32 UTC by koushikk655

2023-08-28 09:54 UTC, chirag-udeshi requested changes

2023-08-28 09:54 UTC, chirag-udeshi commented on Week-1/Assignment-2.1/poem-webpage.html
> +    <p>By <em>Emily Dickinson</em> (1891)</p>
<cite> tag is missing.

2023-08-28 09:54 UTC, chirag-udeshi commented on Week-1/Assignment-2.2/home.html
> +<!DOCTYPE html>
Read the question again and reattempt.

2023-08-28 09:54 UTC, chirag-udeshi commented on Week-1/Assignment-2.3/index.html
> +
footer tag is missing.

2023-12-31 07:40 UTC, chirag7 approved these changes

2024-01-09 19:30 UTC, merged